# Generated by Django 3.1.1 on 2020-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('position_X', models.IntegerField(blank=True, default=0)),
                ('position_Y', models.IntegerField(blank=True, default=0)),
                ('position_Z', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
