# Generated by Django 3.1.1 on 2020-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='tittle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
